[workspace]
resolver = "3"
members = ["pdp11", "pdp11-core", "pdp11-common", "pdp11-asm", "pdp11-asm-cli"]

[workspace.package]
edition = "2024"
version = "0.0.1"


[workspace.dependencies]
pdp11-common = { path = "pdp11-common" }
pdp11-core = { path = "pdp11-core" }
pdp11-asm = { path = "pdp11-asm" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libc = "0.2"


[workspace.lints.clippy]
inefficient_to_string = "warn"
map_flatten = "warn"
map_unwrap_or = "warn"
large_futures = "warn"
unused_async = "warn"
use_self = "warn"


[workspace.lints.rust]
future_incompatible = "warn"
rust_2018_compatibility = "warn"
rust_2021_compatibility = "warn"
rust_2024_compatibility = "warn"
rust_2018_idioms = "warn"
# rust_2024_compatibility = "warn"
unused = "warn"
deprecated_in_future = "warn"
# non_exhaustive_omitted_patterns = "warn"
noop_method_call = "warn"
# unreachable_pub = "warn"
missing_debug_implementations = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
# unused_crate_dependencies = "warn"
unused_lifetimes = "warn"
unused_qualifications = "warn"
warnings = "deny"
